### PR TITLE
Increase default timeout to 24h, simplify exception message

### LINKED ISSUE #42: Remove the default timeout
At the moment (in Armlet 1.1.0) the default request timeout is set to 30 seconds, with is too short for a quick analysis to complete. Also, this assumes by default that the user isn't running a full analysis.

I suggest that we do not set an timeout in armlet by default as this is handled on the server side (we can still support it as an optional parameter. WDYT?

### PR DESCRIPTION
**Pull request by muellerberndt**
Fixes #42

### CODE REVIEW

File: lib/poller.js [hunk 1]
```diff
@@ -13,9 +13,7 @@ function failOnTimeout (timeout, uuid) {
   const t = moment.duration(timeout).as('seconds')
   /* eslint-disable no-throw-literal */
   throw (
-    `User-specified or default time out reached after ${t} seconds.\n` +
-    'Analysis continues on server and may have completed; so run again?\n' +
-    `For status reference, UUID is ${uuid}\n`
+    `Client time out reached after ${t} seconds. UID: ${uuid}\n`
```
Comment (rocky) [inline lib/poller.js]: typo UID -> UUID

File: example/analysis [hunk 2]
```diff
@@ -28,9 +28,10 @@ if (argLen === 3 &&
     usage()
 }
 
-// 60 seconds is a reasonable minimum timeout; For a "quick" analysis
-// the backend uses a value of 30 seconds.
-let timeout = 60
+// A "quick" analysis usually finishes within 90 seconds after the job starts.
+// A "full" analysis may run for 2 hours or more.
+
+let timeout = 86400
```
Comment (rocky) [inline example/analysis:34]: Thanks for the updated information on what MythX execution times are. I was a bit unsure about that.  Is it really true the MythX can run for up to a day?

File: lib/poller.js (hunk 1 above)
Comment (muellerberndt) [reply lib/poller.js]: Oops.. fixed!

File: example/analysis (hunk 2 above)
Comment (muellerberndt) [reply example/analysis:34]: I would say it shouldn't, realistically it would be up to ~3 hours in full mode unless it really get stuck (but then again, we don't really know :))

86400 is kind of synonymous for "run indefinitely, unless something really really isn't right".

File: lib/poller.js [hunk 3]
```diff
@@ -13,9 +13,7 @@ function failOnTimeout (timeout, uuid) {
   const t = moment.duration(timeout).as('seconds')
   /* eslint-disable no-throw-literal */
   throw (
-    `User-specified or default time out reached after ${t} seconds.\n` +
-    'Analysis continues on server and may have completed; so run again?\n' +
```
Comment (rocky) [inline lib/poller.js:17]: The reason I liked the above line is that in general for error messages I keep in mind: what I saw and what the remediation is, if there is one. 

That said, I don't have strong feelings on this.

Comment (muellerberndt) [reply lib/poller.js:17]: True, but the remediation may also depend on the client. For example, in an IDE this particular error message might not make sense.

Comment (rocky) [reply lib/poller.js:17]: But since this is a "throw" the IDE can just ignore it in the "catch".

Comment (muellerberndt) [reply lib/poller.js:17]: Updated.

**Review by rocky — APPROVED** [review]
LGTM
